export enum BookingServiceProviders {
  EXTERNAL_API_INTEGRATION_SERVICE_CLIENT = 'BookingServiceProviders.EXTERNAL_API_INTEGRATION_SERVICE_CLIENT',
  FLIGHTS_SERVICE_CLIENT = 'BookingServiceProviders.FLIGHTS_SERVICE_CLIENT',
  PAYMENTS_SERVICE_CLIENT = 'BookingServiceProviders.PAYMENTS_SERVICE_CLIENT',
}
